version: "3"

tasks:
  setup:
    desc: "Setup Rust"
    cmds:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

  versions:
    desc: "Show Rust versions"
    cmds:
      - rustc --version
      - cargo --version

  run:
    desc: "Run Rust application"
    cmds:
      - cargo run

  dev:
    desc: "Run Rust application with hot-reloading on changes"
    cmds:
      - watchexec -e rs -r cargo run

  check:
    desc: "Check Rust code"
    cmds:
      - task: fix
      - task: lint
      - task: test

  build:
    desc: "Build Rust application"
    cmds:
      - cargo build

  build:release:
    desc: "Build Rust application in release mode"
    cmds:
      - cargo build --release

  test:
    desc: "Run Rust tests"
    cmds:
      - cargo test -- --nocapture

  fix:
    desc: "Fix lint and format Rust code"
    cmds:
      - task: lint:fix
      - task: fmt

  lint:
    desc: "Lint Rust code"
    cmds:
      - cargo clippy --all-targets --all-features --no-deps

  lint:fix:
    desc: "Fix lint Rust code"
    cmds:
      - cargo clippy --all-targets --all-features --no-deps --fix --allow-dirty

  fmt:
    desc: "Format Rust code"
    cmds:
      - cargo fmt

  clean:
    desc: "Clean Rust build artifacts"
    cmds:
      - cargo clean
